name: ogong-deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file

        run: |
          echo "PORT=$PORT" >> .env
          echo "MONGO_URI=$MONGO_URI" >> .env
          echo "CLIENT_URL=$CLIENT_URL" >> .env

        env:
          PORT: ${{ secrets.PORT }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          CLIENT_URL: ${{ secrets.CLIENT_URL }}

      - name: Copy .env to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          source: "./.env"
          target: "/home/ubuntu/Server-V2/backend"

      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /home/ubuntu/Server-V2/backend
            git pull origin main
            pm2 kill
            # Install NVM and Node.js on the remote server
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 22.0.0
            nvm use 22.0.0
            npm i --force
            pm2 start app.js
